import { v } from "convex/values";

export const applicationStatus = v.union(
  v.literal("draft"),
  v.literal("submitted"),
  v.literal("accepted"),
  v.literal("waitlisted"),
  v.literal("rejected"),
  v.literal("withdrawn"),
);

export const eligibilityStatus = v.union(
  v.literal("unreviewed"),
  v.literal("eligible"),
  v.literal("ineligible"),
);

export const application = v.object({
  hackathonId: v.string(),
  status: applicationStatus,
  eligibilityStatus,
  submittedAt: v.optional(v.number()),
  reviewedAt: v.optional(v.number()),
  reviewedBy: v.optional(v.string()),
  checkedInAt: v.optional(v.number()),
  updatedAt: v.number(),
  resumeStorageId: v.optional(v.id("_storage")),
  email: v.optional(v.string()),
  firstName: v.optional(v.string()),
  lastName: v.optional(v.string()),
  phone: v.optional(v.string()),
  age: v.optional(v.number()),
  school: v.optional(v.string()),
  countryOfResidence: v.optional(v.string()),
  levelOfStudy: v.optional(v.string()),
  major: v.optional(v.string()),
  otherRaceEthnicity: v.optional(v.string()),
  graduationYear: v.optional(v.number()),
  gender: v.optional(v.string()),
  raceEthnicity: v.optional(v.array(v.string())),
  dietaryRestrictions: v.optional(v.array(v.string())),
  otherDietary: v.optional(v.string()),
  tshirtSize: v.optional(v.string()),
  firstHackathon: v.optional(v.boolean()),
  hearAbout: v.optional(v.string()),
  linkedin: v.optional(v.string()),
  github: v.optional(v.string()),
  portfolio: v.optional(v.string()),
  accessibilityNeeds: v.optional(v.string()),
  emergencyContactName: v.optional(v.string()),
  emergencyContactPhone: v.optional(v.string()),
  codeOfConductAgreed: v.optional(v.boolean()),
  mlhDataSharingConsent: v.optional(v.boolean()),
  mlhCommunicationsConsent: v.optional(v.boolean()),
});
